# Generated by Django 5.2.11 on 2026-03-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_seed_default_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('director', 'Direktor'), ('seller', 'Sotuvchi'), ('warehouse', 'Omborchi'), ('supplier', 'Yetkazib beruvchi')], default='seller', max_length=20),
        ),
    ]
