# Generated by Django 5.2.11 on 2026-03-31 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_seed_supplier_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramorder',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('confirmed', 'Tasdiqlangan'), ('delivering', 'Yetkazib berilyapti'), ('cancelled', 'Bekor qilingan'), ('completed', 'Yakunlangan')], default='new', max_length=20, verbose_name='Holat'),
        ),
    ]
