# Generated by Django 5.2.11 on 2026-03-31 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_telegramlinkcode_telegramprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Buyurtmachi ismi')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon')),
                ('comment', models.TextField(blank=True, verbose_name='Izoh')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('confirmed', 'Tasdiqlangan'), ('cancelled', 'Bekor qilingan'), ('completed', 'Yakunlangan')], default='new', max_length=20, verbose_name='Holat')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Jami summa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.telegramprofile')),
            ],
            options={
                'verbose_name': 'Telegram buyurtma',
                'verbose_name_plural': 'Telegram buyurtmalar',
            },
        ),
        migrations.CreateModel(
            name='TelegramOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Soni')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Birlik narxi')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Jami narx')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.telegramorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_order_items', to='main.product')),
            ],
            options={
                'verbose_name': 'Telegram buyurtma elementi',
                'verbose_name_plural': 'Telegram buyurtma elementlari',
            },
        ),
    ]
