# Generated by Django 5.2.11 on 2026-03-31 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_telegramorder_telegramorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramorder',
            name='sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_order', to='main.sale'),
        ),
    ]
